// Nível 5 - Meu primeiro site cringe/clientes/livros-react/src/LivroLista.tsx
import { useEffect, useState } from "react";
import { ControleEditora } from "./controle/ControleEditora";
import { ControleLivros } from "./controle/ControleLivros";
import { Livro } from "./modelo/Livro";

interface PropsLinha {
  livro: Livro;
  excluir: (codico: string) => void;
  nomeEditora: string;
}

const controleLivros = ControleLivros;
const controleEditoras = ControleEditora;

export default function LivroLista() {
  const [livros, setLivros] = useState<Livro[]>();
  const [carregado, setCarregado] = useState<boolean>(false);

  const fetchData =async () => {
    const data = await controleLivros.obterLivros();
    console.log(data)
    const livrosTratados = data.map((livro): Livro => ({
      autores: livro.autores,
      codEditora: livro.codEditora,
      codico: String(livro._id),
      resumo: livro.resumo,
      titulo: livro.titulo
    }))
    return livrosTratados
  }

  useEffect(() => {
    const data = fetchData()
    data.then((res) => {
      setLivros(res)
    })
    setCarregado(true);
  }, [carregado]);

  const excluir = (codicoLivro: string) => {
    controleLivros.excluirLivro(codicoLivro);
    
    setCarregado(false);
  };

  return (
    <>
      <h1 className="h1">Catálogo de Livros</h1>
      <table className="table table-light">
        <thead className="table-dark">
          <tr>
            <th className="col-2">Titulo</th>
            <th className="col-6">Resumo</th>
            <th className="col-2">Editora</th>
            <th className="col-2">Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros?.map((livro) => (
            <LinhaLivro
              livro={livro}
              nomeEditora={controleEditoras.getNomeEditora(livro.codEditora)}
              excluir={excluir}
              key={livro.codico}
            />
            
          ))}
        </tbody>
      </table>
    </>
  );
}

function LinhaLivro({ livro, excluir, nomeEditora }: PropsLinha) {
  return (
    <tr>
      <td>
        {livro.titulo} <br />
        <button
          className="btn btn-danger"
          onClick={() => {
            excluir(livro.codico);
          }}
        >
          Excluir
        </button>
      </td>

      <td>{livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
}

// Nível 5 - Vamos Colocar o Framework Para Acessar um Banco/clientes/livros-angular-master/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit{
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  constructor(
    private servEditora: ControleEditoraService, 
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.carregaLivros()
  }

  carregaLivros() {
    this.servLivros.obterLivros().subscribe((listaLivros) => {
      this.livros = this.servLivros.mapearLivros(listaLivros)
    });
  }

  excluir = (codico: string) => {
    this.servLivros.excluirLivro(codico).subscribe(()=>{
      this.carregaLivros()
    })
    // this.servLivros.excluirLivro(codico);
    // this.livros = this.servLivros.obterLivros();
  }

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora)
  }

}

<main>
    <h1 class="h1">Catálogo Livros</h1>
    <table class="table table-light">
        <thead class="table-dark">
            <tr>
                <th class="col-2">Titulo</th>
                <th class="col-6">Resumo</th>
                <th class="col-2">Editora</th>
                <th class="col-2">Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td>{{ livro.titulo }} <br> <button class="btn btn-danger" (click)="excluir(livro.codico)">Excluir</button></td>
                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(livro.codEditora) }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
                
            </tr>
        </tbody>
    </table>
</main>
