// Nível 5 - Vamos Colocar o Framework Para Acessar um Banco/clientes/livros-angular-master/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = {
    titulo: '',
    codico: '0',
    codEditora: 0,
    autores: [],
    resumo: ''
  }

  public autoresForm: string = "";
  public editoras: Array<Editora> = []

  constructor(
    private servEditora: ControleEditoraService, 
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split("\n")
    this.servLivros.incluirLivro({...this.livro, codEditora: +this.livro.codEditora}).subscribe(() => {
      this.router.navigate(["/lista"])
    });
  }
}

<main class="container-fluid">
  <h1>Dados do Livro</h1>

  <form (submit)="incluir()" ngNativeValidate>
    <div class="mb-3">
      <label for="titulo">Título</label>
      <input
        class="form-control"
        type="text"
        [(ngModel)]="livro.titulo"
        required
        name="titulo"
        id="titulo"
      />
    </div>

    <div class="mb-3">
      <label for="resumo">Resumo</label>
      <textarea
        class="form-control"
        [(ngModel)]="livro.resumo"
        name="resumo"
        id="resumo"
        rows="5"
      ></textarea>
    </div>

    <div class="mb-3">
      <label for="editora">Editora</label>
      <select class="form-select" id="editora" [(ngModel)]="livro.codEditora" name="codEditora">
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>

    <div class="mb-3">
      <label for="autores"></label>
      <textarea
        class="form-control"
        name="autores"
        [(ngModel)]="autoresForm"
        id="autores"
        rows="6"
      ></textarea>
    </div>

    <button class="btn btn-primary">Salvar Dados</button>
  </form>
</main>

// Nível 5 - Meu primeiro site cringe/clientes/livros-next/pages/LivroDados.tsx
import { useState } from "react";
import { ControleEditora } from "../classes/controle/ControleEditora"
import { Livro } from "../classes/modelo/Livro";
import { useRouter } from "next/router";

import { ControleLivros } from "../classes/controle/ControleLivros";



const controleLivros = ControleLivros;
const controleEditora = ControleEditora;


export default function LivroDados() {
    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }))
    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0].value);
    const router = useRouter()
    

    function tratarCombo(evento: React.ChangeEvent<HTMLSelectElement>) {
        setCodEditora(Number(evento.target.value))
    }

    async function incluir(evento: React.MouseEvent<HTMLButtonElement, MouseEvent>) {
        evento.preventDefault();
        const livro: Livro = {
            autores: autores.split("\n"),
            codEditora: codEditora,
            resumo: resumo,
            titulo: titulo,
            codico: "0"
        }
        controleLivros.incluirLivro(livro)

        
        router.push('/LivroLista')
        
       
    }   

    return (
        <main className="container-fluid">
            <h1>Dados do Livro</h1>
            <form action="">
                <div className='mb-3'>
                    <label htmlFor="titulo">Título</label>
                    <input className="form-control" type="text" id="titulo" onChange={(evento) => {
                        setTitulo(evento.target.value)
                    }} />
                </div>


                <div className='mb-3'>
                    <label htmlFor="resumo">
                        Resumo</label>
                    <textarea className="form-control" name="" id="resumo" cols={40} rows={5} onChange={(evento) => {
                        setResumo(evento.target.value)
                    }}></textarea>
                </div>


                <div className='mb-3'>
                    <label htmlFor="editora">
                        Editora</label>
                    <select className="form-select" name="editora" id="" onChange={(evento) => {
                        tratarCombo(evento)
                    }}>
                        {opcoes.map(editora => (
                            <option key={editora.value} value={editora.value}>{editora.text}</option>
                        ))}
                    </select>
                </div>

                <div className='mb-3'>
                    <label htmlFor="autores">
                        Autores (1 por linha)</label>
                    <textarea className="form-control" name="" id="autores" cols={40} rows={6} onChange={evento => setAutores(evento.target.value)}></textarea>
                </div>



                <button className="btn btn-primary" onClick={evento => incluir(evento)}>Salvar Dados</button>
            </form>
        </main>
    )
}
