// Nível 5 - Meu primeiro site cringe/clientes/livros-react/src/App.tsx
import './App.css';
import { Link, Outlet } from 'react-router-dom';



function App() {
  return (
    <>
      
      <nav className='navbar bg-dark'>
        <div className='container-fluid d-flex justify-content-start'> 
          <Link className='navbar-brand ms-3 text-light' to={'/'}>Catálogo</Link>
          <Link className='navbar-brand ms-3 text-light' to={'/dados'}>Novo</Link>
        </div>
      </nav>
      

      
      <Outlet></Outlet>
      
    </>
  );
}

export default App;

// Nível 5 - Vamos Colocar o Framework Para Acessar um Banco/clientes/livros-angular-master/src/app/app.component.ts
import { Component } from '@angular/core';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'livros-angular';
  

  
}

<nav class="navbar bg-dark">
    <div class="container-fluid d-flex justify-content-start">
        <a class="navbar-brand ms-3 text-light" routerLink="/lista">Catálogo</a>
        <a class="navbar-brand ms-3 text-light" routerLink="/dados">Novo</a>
    </div>
</nav>
<router-outlet></router-outlet>
