// Nível 5 - Vamos Colocar o Framework Para Acessar um Banco/clientes/livros-angular-master/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = {
    titulo: '',
    codico: '0',
    codEditora: 0,
    autores: [],
    resumo: ''
  }

  public autoresForm: string = "";
  public editoras: Array<Editora> = []

  constructor(
    private servEditora: ControleEditoraService, 
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split("\n")
    this.servLivros.incluirLivro({...this.livro, codEditora: +this.livro.codEditora}).subscribe(() => {
      this.router.navigate(["/lista"])
    });
  }
}

<main class="container-fluid">
  <h1>Dados do Livro</h1>

  <form (submit)="incluir()" ngNativeValidate>
    <div class="mb-3">
      <label for="titulo">Título</label>
      <input
        class="form-control"
        type="text"
        [(ngModel)]="livro.titulo"
        required
        name="titulo"
        id="titulo"
      />
    </div>

    <div class="mb-3">
      <label for="resumo">Resumo</label>
      <textarea
        class="form-control"
        [(ngModel)]="livro.resumo"
        name="resumo"
        id="resumo"
        rows="5"
      ></textarea>
    </div>

    <div class="mb-3">
      <label for="editora">Editora</label>
      <select class="form-select" id="editora" [(ngModel)]="livro.codEditora" name="codEditora">
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>

    <div class="mb-3">
      <label for="autores"></label>
      <textarea
        class="form-control"
        name="autores"
        [(ngModel)]="autoresForm"
        id="autores"
        rows="6"
      ></textarea>
    </div>

    <button class="btn btn-primary">Salvar Dados</button>
  </form>
</main>

// Nível 3 - Meu Primeiro Framework/livros-react/src/LivroDados.tsx
import React from "react";
import { ControleLivro } from "./controle/ControleLivros";
import { ControleEditora} from "./controle/ControleEditora";
import { useNavigate } from "react-router-dom";

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

export default function LivroDados(){
    const navigate = useNavigate();
    const opcoes = controleEditora.getEditoras;

    const [titulo, setTitulo] = React.useState<string>("");
    const [resumo, setResumo] = React.useState<string>("");
    const [autores, setAutores] = React.useState<string>("");
    const [codEditora, setcodEditora] = React.useState<number>(0); 

    function tratarCombo(event: React.ChangeEvent<HTMLSelectElement>) {
        setcodEditora(parseInt(event.target.value));
    }

    function incluir(event: React.FormEvent<HTMLFormElement>) {
        event.preventDefault();
    
        const livro = {
          codigo: 0,
          codEditora,
          titulo,
          resumo,
          autores: autores.split("\n")
        };
        controleLivro.incluir(livro);
        navigate("/");
    }

    return (
        <main>
            <div>
                <h1>Dados do Livro</h1>
            </div>
            <form onSubmit={(event) => incluir(event)}>
                <div className="form-group">
                    <label htmlFor="exampleInputEmail1">Titulo</label>
                    <input className="form-control mb-2" id="titulo" type="text" value={titulo} onChange={(event) => setTitulo(event.target.value)}></input>
                </div>
                <div className="form-group">
                    <label htmlFor="exampleInputEmail1">Resumo</label>
                    <textarea className="form-control mb-2" id="resumo" value={resumo} onChange={(event) => setResumo(event.target.value)} rows={3}></textarea>
                </div>
                <div className="form-group">
                    <label htmlFor="exampleFormControlSelect1">Editora</label>
                    <select className="form-control mb-4" id="editora" value={codEditora} onChange={(event) => {tratarCombo(event);}}>
                        {
                        controleEditora.getEditoras().map((editora) => {
                            return (
                            <option value={Number(editora.codEditora)}>{editora.nome}</option>
                            );
                        })}
                    </select>
                </div>
                <div className="form-group">
                    <label htmlFor="exampleInputEmail1">Autores (1 por linha)</label>
                    <textarea className="form-control mb-2" id="autores" value={autores} onChange={(event) => setAutores(event.target.value)} rows={3}></textarea>
                </div>
                <div>
                    <button type="submit" className="btn btn-primary mb-2">Salvar Dados</button>
                </div>
            </form>
        </main>
    );
}
