// Nível 5 - Vamos Colocar o Framework Para Acessar um Banco/clientes/livros-angular-master/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit{
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  constructor(
    private servEditora: ControleEditoraService, 
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.carregaLivros()
  }

  carregaLivros() {
    this.servLivros.obterLivros().subscribe((listaLivros) => {
      this.livros = this.servLivros.mapearLivros(listaLivros)
    });
  }

  excluir = (codico: string) => {
    this.servLivros.excluirLivro(codico).subscribe(()=>{
      this.carregaLivros()
    })
    // this.servLivros.excluirLivro(codico);
    // this.livros = this.servLivros.obterLivros();
  }

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora)
  }

}

<main>
    <h1 class="h1">Catálogo Livros</h1>
    <table class="table table-light">
        <thead class="table-dark">
            <tr>
                <th class="col-2">Titulo</th>
                <th class="col-6">Resumo</th>
                <th class="col-2">Editora</th>
                <th class="col-2">Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td>{{ livro.titulo }} <br> <button class="btn btn-danger" (click)="excluir(livro.codico)">Excluir</button></td>
                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(livro.codEditora) }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
                
            </tr>
        </tbody>
    </table>
</main>

// Nível 3 - Meu Primeiro Framework/livros-react/src/LivroLista.tsx
import { ControleLivro } from "./controle/ControleLivros";
import { ControleEditora } from "./controle/ControleEditora";
import React from "react";
import { Livro } from "./modelo/Livro";

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

type props = {
    livro: Livro;
    excluir: ControleLivro;
    carregado: React.Dispatch<React.SetStateAction<boolean>>;
}

const LinhaLivro = ({livro, excluir, carregado}: props) => {
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);
    return(
        <tr>
            <td scope="row">{livro.titulo}<br/>
                <button type="button" 
                        className="btn btn-danger btn-sm"
                        onClick={() => {
                            excluir.excluir(livro.codigo);
                            carregado(true);
                        }}>Excluir</button>
            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>
                <ul>
                    {livro.autores.map((nome) => {return <li>{nome}</li>;})}
                </ul>
            </td>
        </tr>
    );
}

export default function LivroLista(){
    const [livros, setLivros] = React.useState<Livro[]>(controleLivro.obterLivros());
    const [carregado, setCarregado] = React.useState<boolean>(false);

    React.useEffect(() => {
        setLivros(controleLivro.obterLivros());
        setCarregado(true);
    }, [carregado]);


    return (
        <main>
            <div>
                <h1>Catálogo de Livros</h1>
            </div>
            <table className="table">
                <thead className="thead-dark">
                        <tr>
                        <th scope="col">Título</th>
                        <th scope="col">Resumo</th>
                        <th scope="col">Editora</th>
                        <th scope="col">Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {
                    livros.map((livro) => {
                        return (
                        <LinhaLivro key={livro.codigo}livro={livro}carregado={setCarregado}excluir={controleLivro}/>
                        );
                    })}
                </tbody>
            </table>
        </main>
    );
}
